language: scala
scala:
  - 2.11.8
jdk:
  - oraclejdk8
install:
  - . $HOME/.nvm/nvm.sh
  - nvm install stable
  - nvm use stable
  - npm install
  - npm install jsdom
script:
  - sbt clean coverage test
after_success:
  - sbt coverageReport
  - sbt coverageAggregate
  - sbt codacyCoverage

# Ivy cache
before_cache:
  # Cleanup the cached directories to avoid unnecessary cache updates
  - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete
  - find $HOME/.sbt        -name "*.lock"               -print -delete
cache:
  directories:
    # These directories are cached to S3 at the end of the build
    - $HOME/.ivy2/cache
    - $HOME/.sbt
